sudo: required

services:
  - docker

script:
  - pwd
  - whoami
  - id -u
  - id -g
  - su - travis
  - make up SERVICE='develop python firefox'
  - make clean
  - make fetch
  - make lint
  - make build CONFIG=production
  - make unit-test
  - make e2e-test
  - make down
