version: "3"

services:
  develop:
    build:
      context: .
      dockerfile: ./dockerfiles/develop/Dockerfile
    environment:
      - HOME=/usr/src/app/cache/develop/home
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  selenium-hub:
    image: selenium/hub:3.141.59-gold
    expose:
      - "4444"
    ports:
      # Can watch state on http://localhost:${DynamicPort}/grid/console
      - "4444"
  chrome:
    image: selenium/node-chrome:3.141.59-gold
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - .:/usr/src/app
  chrome-debug:
    image: selenium/node-chrome-debug:3.141.59-gold
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      # vnc port to access like following:
      # $ echo 'secret' | vncviewer -autopass 127.0.0.1:5900
      - 5900:5900
    volumes:
      - .:/usr/src/app
  firefox:
    image: selenium/node-firefox:3.141.59-gold
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - .:/usr/src/app
  firefox-debug:
    image: selenium/node-firefox-debug:3.141.59-gold
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      # vnc port to access like following:
      # $ echo 'secret' | vncviewer -autopass 127.0.0.1:5900
      - 5900:5900
    volumes:
      - .:/usr/src/app
  python:
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
