name: audit

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: make up SERVICE='develop'
    - run: make clean TTY=false
    - run: make sync TTY=false
    - run: make audit TTY=false
    - run: make down
